### ISSUE TITLE
[All the Mods v3.03] [MC v1.10.2] Crash when adding DynmapBlockScan

### ISSUE THREAD

**Issue by kaiserdj** [webbukkit/DynmapBlockScan#12] opened 2017-10-28 23:20 UTC
https://gist.github.com/kaiserdj/5d883d62d4002477f07cd8bcd326bfd5

**Comment by hcardwell** [comment] 2017-11-07 17:58
I believe I have the identical crash in a variation on that modpack.  I am running ATM: Expert Remastered v1.1.1, but it appears to be the same crash. 

Full log:
https://gist.github.com/hcardwell/cdc41bc0b6ea5caa195fd299579f01b4

Relevant snippet:
[12:42:37] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[12:42:37] [Server thread/ERROR] [FML/]: Caught exception from DynmapBlockScan (dynmapblockscan)
java.lang.NullPointerException
	at org.dynmap.blockscan.blockstate.Variant$Deserializer.deserialize(Variant.java:111) ~[Variant$Deserializer.class:?]
	at org.dynmap.blockscan.blockstate.Variant$Deserializer.deserialize(Variant.java:105) ~[Variant$Deserializer.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]

**Comment by kaiserdj** [comment] 2017-11-08 13:03
Pliss fixed this

**Comment by adampaulberg** [comment] 2017-11-11 02:23
I am having this same issue. It's failing on both Windows and Ubuntu

**Comment by mikeprimm** [comment] 2018-01-06 16:48
@kaiserdj DynmapBlockScan is server only - your initial report shows a forge client log : it MIGHT work standalone/SSP, but no promises.

Try latest builds of DynmapBlockScan and DynmapForge - patch applied that should handle what looks to be the cause of these exceptions.

**Comment by hcardwell** [comment] 2018-01-06 17:23
@mikeprimm Hijacking reply as I made the same error?  For what it's worth, I was under the impression that Dynmap itself was functionally server-only, but the block scan stuff needed the client rendering engine running to get the textures / voxel type to build the cache.  So I was running DynmapBlockScan in a client in order to build the cache to drop on the server.  I'll try the new builds later today and provide more feedback as I am able.  Thanks for the work!

**Comment by mikeprimm** [comment] 2018-01-06 18:15
You're assuming DynmapBlockScan works like the older DynmapModScraper - which is understandable, but incorrect.  DynmapBlockScan never needs to be on a client, and is expected to ultimately be merged with Dynmap itself (once I get more time to finish the core implementation and the rest - it's kind of a huge effort...).  That said, it probably CAN work on an SSP system, but I honestly haven't tested it (or considered doing so as a priority, at least during the alpha/primary development stage).  In any case, the patch I just made SHOULD help - or, at least, affect - the problem you saw, so give it a spin and let me know if new or different 'smoke' comes out.

**Comment by adampaulberg** [comment] 2018-01-07 04:40
I couldn't successfully get gradle to build this.  Will this code build into http://www.dynmap.us/builds/DynmapBlockScan/ ?

**Comment by hcardwell** [comment] 2018-01-09 15:32
@mikeprimm Sorry for the delays.  Your January 6 builds do indeed run on my ATM:Expert Remastered 1.1.1 server.  The Dynmap view is rendering a few additional block types from mods, but many (most?) mod blocks still are not rendering.  Some are mis-rendering (presumably entity types rather than blocks?) like cables rendering as bedrock.  I had cleared all the map contents and did a radius render for testing.  If there is utility in seeing the logs let me know and I'll upload them.  Thank again for your continued work on this mod.  I think it is really awesome.

**Comment by mikeprimm** [comment] 2018-02-11 16:15
Please try latest version of Dynmap v3.0 and DynmapBlockScan - there have been a couple of other fixes that, in particular, help with 1.10.2 (which is a version that I backported to, by request, but hasn't been the primary focus of the DynmapBlockScan and v3.0 development).

**Comment by hcardwell** [comment] 2018-02-11 17:07
@mikeprimm I do not see commits for DynmapBlockScan on Github newer than the Jan 6 ones that I believe are in the current builds posted under dynamp.us/builds.  Checked both Master and the 1.10.2 branch.  Also, buddies and I finished ATM:Expert Remastered and moved to Age of Engineering.  Still a 1.10.2 modpack, but makes this thread issue title even less relevant.  Happy to continue help testing as I am able though.  I think Dynmap is awesome.  Thanks!

**Comment by hcardwell** [comment] 2018-02-11 22:19
Follow-up: with today's build of DynMap and the Jan 6 build of DynmapBlockScan, a few mod-based voxels (notably ones from Forestry) are rendering fine.  Most do not appear to be, and render as black squares in "Flat" and black voxels in "surface".  No crashes or anything, and renders appear performant.  Let me know what else I can do.   Not an exhaustive test, but I will leave it running to report back.

**Closed** 2018-12-08 23:48 UTC
Labels: Fixed, bug
